on:
  push:
    branches:
      - develop      
jobs:
  BuildPre:
    runs-on: windows-latest  
    name: BuildPre
    steps:
    - name: BuildPre
      uses: actions/checkout@v2
    - run: echo Hello.
      shell: bash
    - run: echo "Nice to meet you!"
      shell: pwsh
