on:
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
inputs:
  name: 
    description: 'Your name'
    default: 'No name provided'
runs:
  using: "composite"
  steps: 
    - run: echo Hello.
      shell: bash
    - run: echo "Nice to meet you!"
      shell: pwsh