on:
  push:
    branches:
      - develop      
jobs:
  BuildPre:
    runs-on: windows-latest  
    name: BuildPre
    steps:
    - name: BuildPre
      uses: actions/checkout@v2
    - run: rd /s /q C:\Users\ivan.moraga\source\repos\blog-net-core-security-copy
      shell: cmd
