on:
  pull_request:
    branches:
      - develop
inputs:
  name: 
    description: 'Your name'
    default: 'No name provided'
runs:
  using: "composite"
  steps: 
    - run: echo Hello.
      shell: bash
    - run: echo "Nice to meet you!"
      shell: pwsh