on:
  push:
    branches:
      - develop      
jobs:
  BuildPre:
    runs-on: windows-latest  
    name: BuildPre
    steps:
    - name: BuildPre
      uses: actions/checkout@v2
    - run: ls -la
      shell: bash
    - run: prueba.sh
      shell: bash
